// File generated by FlutterFire CLI.
// TODO: this is a PLACEHOLDER. Run `flutterfire configure` in the project
// root to replace this file with real values from your Firebase project.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to add support for it.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB94lVJe_S9lB8LnbUnYM8dxp3ZpIMht1I',
    appId: '1:1049065579223:web:1c92ec5303a1bbde460692',
    messagingSenderId: '1049065579223',
    projectId: 'manifest-fellowship-tracker',
    authDomain: 'manifest-fellowship-tracker.firebaseapp.com',
    storageBucket: 'manifest-fellowship-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBElHkbjG-rQwtrQ1PyarU5v-3GKagTjBk',
    appId: '1:1049065579223:android:77eaa832ced1775a460692',
    messagingSenderId: '1049065579223',
    projectId: 'manifest-fellowship-tracker',
    storageBucket: 'manifest-fellowship-tracker.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
    iosBundleId: 'com.manifestfellowship.manifestFellowshipTracker',
  );
}
